const { chromium } = require('../.tools/browser/node_modules/playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

(async () => {
  const output = path.resolve('logs/sandbox_qa');
  fs.mkdirSync(output, { recursive: true });
  const browser = await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1080}});
  const errors = [];
  page.on('pageerror', error => errors.push(String(error)));
  const base = process.env.SANDBOX_URL || 'http://127.0.0.1:8877';
  const ready = async () => {
    await page.waitForFunction(() => document.getElementById('job-status').textContent === '就绪', null, {timeout:45000});
    const problem = await page.locator('#error').textContent();
    assert.equal(problem, '', problem);
  };
  const act = async selector => {
    const old = (await (await page.request.get(base+'/api/sandbox/state')).json()).revision;
    await page.locator(selector).click();
    await page.waitForFunction(async ({base,old}) => {
      const state = await (await fetch(base+'/api/sandbox/state')).json();
      if (state.job?.status === 'failed') throw new Error(state.job.error);
      return state.revision > old && !state.busy;
    }, {base,old}, {timeout:45000});
    await ready();
  };
  try {
    await page.goto(base+'/sandbox');
    await page.waitForSelector('.scene-item');
    await page.locator('[data-scene="case_rupture_before_self_damage"]').click();
    await ready();
    await page.waitForSelector('.card-play');
    await page.locator('[data-mode="compare"]').click();
    await page.waitForFunction(()=>[...document.querySelectorAll('.card-art')].some(image=>image.complete&&image.naturalWidth>0));
    assert.ok(await page.locator('.card-art').evaluateAll(images=>images.some(image=>image.complete&&image.naturalWidth>0)));
    const raw = await (await page.request.get(base+'/api/sandbox/state')).json();
    assert.ok(!JSON.stringify(raw).includes('draw_pile'));
    await page.locator('.card-info').first().click();
    await page.waitForSelector('#card-dialog[open]');
    await page.screenshot({path:path.join(output,'card-detail.png')});
    await page.locator('#close-card').click();
    await page.locator('.card-play[data-card="0"]').click();
    await act('.enemy.targetable');
    await act('#undo');
    assert.equal(await page.locator('.card-play').count(),5);
    await act('#redo');
    assert.equal(await page.locator('.card-play').count(),4);
    await act('#reset');
    await act('#end-turn');
    await page.locator('#plan-name').fill('QA 原地结束');
    await act('#save-plan');
    await act('#reset');
    await act('.hand-card:has(.card-name:text-is("撕裂")) .card-play');
    await page.locator('.hand-card:has(.card-name:text-is("御血术")) .card-play').click();
    await act('.enemy.targetable');
    await act('#end-turn');
    await page.locator('#plan-name').fill('QA 撕裂联动');
    await act('#save-plan');
    await page.locator('input[name=preference][value=b]').check();
    await page.locator('#annotation-note').fill('浏览器自动验收数据，不用于训练');
    await act('#save-label');
    await act('#agent-plan');
    await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});
    await page.locator('#new-scene').click();
    await page.locator('[name=title]').fill('QA 手工场景');
    await page.locator('[name=seed]').fill('sandbox-browser');
    await page.locator('[name=hp]').fill('42');
    await page.locator('[name=energy]').fill('4');
    await page.locator('[name=enemy_hp]').fill('40');
    await page.locator('[name=upgrade_hand]').check();
    await page.locator('#scene-form summary').click();
    for (const id of ['RUPTURE','HEMOKINESIS','DEFEND_IRONCLAD']) await page.locator(`[data-add="${id}"]`).click();
    await page.screenshot({path:path.join(output,'generator.png'),fullPage:true});
    await act('#generate');
    assert.match(await page.locator('#player-hp').textContent(),/^42/);
    assert.equal(await page.locator('#player-energy').textContent(),'4');
    assert.equal(await page.locator('.card-play').count(),3);
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
    await page.setViewportSize({width:1440,height:1080});
    await act('[data-scene="case_potion_search_budget"]');
    await page.locator('[data-potion="0"]').click();
    await act('.enemy.targetable');
    await act('[data-potion]');
    assert.equal(await page.locator('[data-potion]').count(),0);
    const data=await (await page.request.get(base+'/api/sandbox/export')).json();
    assert.ok(data.plans.length>=3 && data.labels.length>=1);
    assert.equal(data.feature_schema.features.length,10);
    assert.deepEqual(errors,[]);
    console.log(JSON.stringify({status:'passed',plans:data.plans.length,labels:data.labels.length,screenshots:output}));
  } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exit(1);});
