'use strict';
(() => {
  const el = id => document.getElementById(id);
  const labels = {a_win:'仅 A 获胜',b_win:'仅 B 获胜',a_resources:'双方胜利 · A 资源领先',b_resources:'双方胜利 · B 资源领先',equal_resources:'双方胜利 · 资源相同',resource_tradeoff:'双方胜利 · 资源取舍',both_lost:'双方战败',excluded:'排除',cancelled:'已停止'};
  const reasons = {baseline_gate:'原实战对照未通过',model_a_gate:'模型 A 重跑不一致',model_b_gate:'模型 B 重跑不一致',live_scorer_unavailable:'找不到原实战评分模型',incomplete_replay:'回放未完成',missing_terminal_resources:'终局资源缺失',unknown_terminal:'未知战斗终局'};
  let catalog = {models:[],snapshots:[],jobs:[]}, selected = new Set(), selectionReady = false, jobId = '', busy = false;
  let draft = {}, abilityDraft = {}, detailId = '';
  const text = (id,value) => { el(id).textContent = value == null ? '—' : String(value); };
  const node = (tag, cls, value) => { const n=document.createElement(tag);if(cls)n.className=cls;if(value!=null)n.textContent=String(value);return n; };
  const msg = value => text('cmp-model-message',value);
  const error = value => {text('cmp-error',value);el('cmp-error').hidden=!value;};
  async function api(path, body) {
    const response = await fetch('/api/comparison/'+path,body === undefined ? {} : {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
    const data = await response.json(); if(!response.ok)throw Error(data.error||'请求失败');return data;
  }
  function options(id, rows, current) {
    const box=el(id);box.replaceChildren();for(const row of rows){const option=node('option','',row.name);option.value=row.id;box.append(option);}if(current&&rows.some(row=>row.id===current))box.value=current;
  }
  function modelById(id){return catalog.models.find(row=>row.id===id);}
  function showDraft(){const container=el('cmp-weights');container.replaceChildren();for(const spec of catalog.features?.features||[]){const label=node('label','comparison-weight');const caption=node('span','',spec.label);caption.title=spec.definition;const range=node('input');range.type='range';range.min='0';range.max='200';range.step='0.1';range.value=String(Math.min(200,draft[spec.key]??0));const number=node('input');number.type='number';number.min='0';number.max='1000';number.step='0.1';number.value=String(draft[spec.key]??0);range.addEventListener('input',()=>{number.value=range.value;draft[spec.key]=Number(range.value);});number.addEventListener('input',()=>{draft[spec.key]=Number(number.value);range.value=String(Math.min(200,Math.max(0,draft[spec.key]||0)));});label.append(caption,range,number);container.append(label);}}
  function showAbilitySettings(){
    for(const id of ['cmp-ability-settings','cmp-ability-advanced-settings'])el(id).replaceChildren();
    for(const spec of catalog.features?.ability_model?.parameters||[]){
      const label=node('label','comparison-weight');
      const caption=node('span','',spec.label);caption.title=spec.description;
      const range=node('input'),number=node('input');range.type='range';number.type='number';
      number.id='cmp-ability-'+spec.key;
      for(const input of [range,number]){input.min=spec.min;input.max=spec.max;input.step=spec.step;input.value=abilityDraft[spec.key];input.setAttribute('aria-label',spec.label);input.title=spec.description;}
      range.addEventListener('input',()=>{number.value=range.value;abilityDraft[spec.key]=Number(range.value);});
      number.addEventListener('input',()=>{abilityDraft[spec.key]=number.value===''?null:Number(number.value);range.value=number.value;});
      label.append(caption,range,number);
      el(spec.advanced?'cmp-ability-advanced-settings':'cmp-ability-settings').append(label);
    }
  }
  function loadEditor(id){const row=modelById(id);if(!row)return;draft={...row.model.weights};abilityDraft=Object.fromEntries((catalog.features?.ability_model?.parameters||[]).map(spec=>[spec.key,row.model.ability_config?.[spec.key]??spec.default]));showDraft();showAbilitySettings();el('cmp-model-name').value=row.source==='active'?'':row.name;msg('已载入 '+row.name+'；修改后请保存为新版本。');el('cmp-delete-model').disabled=row.source!=='saved';el('cmp-rename-model').disabled=row.source==='active';}
  function randomNumber(seed){let value=2166136261;for(const char of seed){value=Math.imul(value^char.charCodeAt(0),16777619);}return ()=>{value+=0x6d2b79f5;let t=Math.imul(value^(value>>>15),1|value);t^=t+Math.imul(t^(t>>>7),61|t);return ((t^(t>>>14))>>>0)/4294967296;};}
  function randomize(){const magnitude=Number(el('cmp-random-percent').value)/100;if(!Number.isFinite(magnitude)||magnitude<=0||magnitude>1){error('扰动幅度须在 1% 到 100% 之间');return;}const seed=el('cmp-random-seed').value.trim();if(!seed){error('请填写随机种子');return;}const next=randomNumber(seed);for(const key of Object.keys(draft))draft[key]=Math.round(Math.max(0,draft[key]*Math.exp((next()*2-1)*magnitude))*1000)/1000;showDraft();msg('已按种子 '+seed+' 生成；尚未保存。');error('');}
  function renderModels(){const oldEditor=el('cmp-editor-source').value,oldA=el('cmp-model-a').value,oldB=el('cmp-model-b').value;const rows=catalog.models;options('cmp-editor-source',rows,oldEditor||'active');options('cmp-model-a',rows,oldA||'active');options('cmp-model-b',rows,oldB||rows.find(row=>row.id!=='active')?.id);loadEditor(el('cmp-editor-source').value);}
  function renderSnapshots(){const box=el('cmp-snapshots');box.replaceChildren();const act=el('cmp-act').value;const rows=catalog.snapshots.filter(row=>act==='all'||String(row.context?.act)===act);if(!rows.length){box.append(node('p','muted','当前范围没有已核验的快照。'));return;}for(const row of rows){const label=node('label','comparison-snapshot');const input=node('input');input.type='checkbox';input.checked=selected.has(row.id);input.addEventListener('change',()=>{if(input.checked)selected.add(row.id);else selected.delete(row.id);updateSelectCount();});const info=node('span','',`第 ${row.floor??'?'} 层 · 回合 ${row.turn??'?'} · ${row.context?.encounter_id||'未知遭遇'} · ${row.id}`);label.append(input,info);box.append(label);}updateSelectCount();}
  function updateSelectCount(){text('cmp-select-all',`选择当前列表（已选 ${selected.size}）`);}
  function renderJobs(){const rows=catalog.jobs.map(row=>({id:row.id,name:`${row.id} · ${row.status} ${row.completed}/${row.total}`}));options('cmp-job-select',rows,jobId||rows[0]?.id);if(!jobId&&rows.length)jobId=rows[0].id;}
  async function refreshCatalog(){catalog=await api('catalog');if(!selectionReady){selected=new Set(catalog.snapshots.slice(0,48).map(row=>row.id));selectionReady=true;}renderModels();renderSnapshots();renderJobs();if(jobId)await refreshJob();}
  function scatter(job){const pairs=(job.pairs||[]).filter(p=>p.status==='VALID'&&Number.isFinite(p.comparison?.hp_delta)&&Number.isFinite(p.comparison?.potion_delta));if(!pairs.length)return null;const box=node('div','comparison-scatter');box.append(node('h3','','每份快照的终局资源差（A−B）'));const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 420 220');svg.setAttribute('role','img');svg.setAttribute('aria-label','生命差与药水数差散点图；点选圆点查看对应战斗');const maxHp=Math.max(5,...pairs.map(p=>Math.abs(p.comparison.hp_delta)));const maxPotion=Math.max(1,...pairs.map(p=>Math.abs(p.comparison.potion_delta)));const x=v=>210+v/maxHp*175,y=v=>110-v/maxPotion*80;for(const [x1,y1,x2,y2] of [[35,110,385,110],[210,25,210,190]]){const line=document.createElementNS(svg.namespaceURI,'line');for(const [key,value] of Object.entries({x1,y1,x2,y2,stroke:'#c5d3cb','stroke-width':1}))line.setAttribute(key,value);svg.append(line);}for(const pair of pairs){const circle=document.createElementNS(svg.namespaceURI,'circle');circle.setAttribute('cx',x(pair.comparison.hp_delta));circle.setAttribute('cy',y(pair.comparison.potion_delta));circle.setAttribute('r',6);circle.setAttribute('fill',pair.comparison.category==='resource_tradeoff'?'#b77a25':'#167153');circle.setAttribute('tabindex','0');circle.setAttribute('aria-label',`${pair.snapshot_id}：生命差 ${pair.comparison.hp_delta}，药水数差 ${pair.comparison.potion_delta}`);const title=document.createElementNS(svg.namespaceURI,'title');title.textContent=`${pair.snapshot_id} · 生命 ${pair.comparison.hp_delta} · 药水 ${pair.comparison.potion_delta}`;circle.append(title);circle.addEventListener('click',()=>showPair(pair.snapshot_id));circle.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();showPair(pair.snapshot_id);}});svg.append(circle);}box.append(svg,node('p','muted','横轴：生命差 · 纵轴：药水数差 · 棕色：资源取舍'));return box;}
  function summary(job){const box=el('cmp-summary');box.replaceChildren();const counts=job.counts||{},total=job.completed||0,valid=Object.entries(counts).filter(([key])=>!['excluded','cancelled'].includes(key)).reduce((sum,[,v])=>sum+v,0);box.append(node('p','comparison-overview',`有效配对 ${valid} / 已处理 ${total} · 排除 ${counts.excluded||0} · 已停止 ${counts.cancelled||0}`));if(valid>0&&valid<10)box.append(node('p','comparison-small-sample','有效样本少于 10 份，汇总仅供观察，暂不代表整体水平。'));const chart=node('div','comparison-chart');for(const [key,count] of Object.entries(counts)){const item=node('div','comparison-chart-row');const title=node('span','',labels[key]||key);const bar=node('div','comparison-bar');const fill=node('span','');fill.style.width=(total?100*count/total:0)+'%';bar.append(fill);item.append(title,bar,node('strong','',count));chart.append(item);}box.append(chart);const plot=scatter(job);if(plot)box.append(plot);const excluded={};for(const pair of job.pairs||[])if(pair.status==='EXCLUDED'){const key=reasons[pair.reason]||pair.reason||'未说明';excluded[key]=(excluded[key]||0)+1;}if(Object.keys(excluded).length)box.append(node('p','comparison-exclusions','排除原因：'+Object.entries(excluded).map(([key,count])=>`${key} ${count}`).join(' · ')));}
  function renderPairs(job){const box=el('cmp-pairs');box.replaceChildren();for(const pair of job.pairs||[]){const button=node('button','comparison-pair');button.type='button';const prefix=pair.context?.floor?`第 ${pair.context.floor} 层 · `:'';const outcome=pair.status==='VALID'?(labels[pair.comparison?.category]||pair.comparison?.category):`排除 · ${reasons[pair.reason]||pair.reason||pair.status}`;button.append(node('strong','',prefix+(pair.context?.encounter_id||pair.snapshot_id)),node('small','',outcome+(pair.first_divergence?` · 第 ${pair.first_divergence} 步分叉`:'')));if(pair.snapshot_id===detailId)button.classList.add('selected');button.addEventListener('click',()=>showPair(pair.snapshot_id));box.append(button);}if(!job.pairs?.length)box.append(node('p','muted','等待首份快照完成。'));}
  const formatState = state => `生命 ${state?.hp??'—'} · 格挡 ${state?.block??'—'} · 药水 ${(state?.potions||[]).length} · 敌人 ${(state?.enemies||[]).map(e=>`${e.id||'?'} ${e.hp??'?'}`).join('、')||'无'}`;
  const formatAction = action => {const chosen=action?.chosen||{};const card=chosen.metadata?.card_id;return `${action?.action||'—'}${card?' · '+card:''}${chosen.target_index!=null?' · 目标 '+chosen.target_index:''}`;};
  function actionColumn(title,run,divergence){const col=node('div','comparison-action-column');col.append(node('h4','',title),node('p','',`终局 ${run.terminal} · ${formatState(run.outcome)}`));for(let i=0;i<(run.actions||[]).length;i++){const row=run.actions[i];const line=node('div','comparison-action'+(i+1===divergence?' diverged':''));line.append(node('strong','',`${i+1}. ${formatAction(row)}`),node('small','',formatState(row.after)));if(row.score!=null)line.append(node('small','',`模型内部评分 ${Number(row.score).toFixed(2)} · ${row.decision_reason||''}`));const contributions=row.score_explanation?.contributions||[];if(contributions.length){const details=node('details','comparison-contributions');details.append(node('summary','','评分拆解'));for(const part of contributions){details.append(node('small','',`${part.label||part.key}: ${Number(part.contribution??part.score??0).toFixed(2)}（权重 ${part.weight??'—'}）`));}line.append(details);}col.append(line);}return col;}
  async function showPair(snapshot){if(!jobId)return;detailId=snapshot;const box=el('cmp-detail');box.replaceChildren(node('p','muted','正在读取单场详情…'));try{const pair=await api('pair?id='+encodeURIComponent(jobId)+'&snapshot='+encodeURIComponent(snapshot));box.replaceChildren();box.append(node('h4','',`快照 ${snapshot}`));if(pair.status!=='VALID'){box.append(node('p','comparison-error',`已排除：${reasons[pair.reason]||pair.reason||pair.status}`));if(pair.aa||pair.history){const gate=pair.aa||{},history=pair.history||{};box.append(node('p','',`重跑 ${gate.status||'—'}${gate.reason?' · '+gate.reason:''}；实战对照 ${history.status||'—'}${history.reason?' · '+history.reason:''}${history.first_difference?' · 第 '+history.first_difference+' 步分叉':''}`));}return;}box.append(node('p','',`${labels[pair.comparison.category]} · 首次动作分叉：${pair.first_divergence??'无'}`));const outcome=node('p','',`生命差 A−B：${pair.comparison.hp_delta}；药水数差 A−B：${pair.comparison.potion_delta}`);box.append(outcome);const cols=node('div','comparison-action-columns');cols.append(actionColumn('模型 A',pair.a,pair.first_divergence),actionColumn('模型 B',pair.b,pair.first_divergence));box.append(cols);}catch(exc){box.replaceChildren(node('p','comparison-error',String(exc)));}}
  async function refreshJob(){if(!jobId)return;try{const job=await api('job?id='+encodeURIComponent(jobId));text('cmp-progress',`${job.a_name||'A'} / ${job.b_name||'B'} · ${job.status} · ${job.completed}/${job.total}${job.error?' · '+job.error:''}`);el('cmp-start').disabled=busy||['starting','running'].includes(job.status);el('cmp-stop').disabled=busy||!['starting','running'].includes(job.status);summary(job);renderPairs(job);}catch(exc){error(exc);}}
  async function saveModel(){try{for(const spec of catalog.features?.ability_model?.parameters||[]){const value=abilityDraft[spec.key];if(!Number.isFinite(value)||value<spec.min||value>spec.max||(spec.key==='max_horizon'&&!Number.isInteger(value)))throw Error(spec.label+'超出允许范围');}busy=true;const saved=await api('model',{name:el('cmp-model-name').value,weights:draft,ability_config:abilityDraft});await refreshCatalog();el('cmp-editor-source').value=saved.id;loadEditor(saved.id);el('cmp-model-b').value=saved.id;msg('已保存 '+saved.name);error('');}catch(exc){error(exc);}finally{busy=false;}}
  async function renameModel(){const id=el('cmp-editor-source').value,row=modelById(id);if(!row||row.source==='active')return;try{const renamed=await api('model/rename',{id,name:el('cmp-model-name').value});await refreshCatalog();el('cmp-editor-source').value=id;loadEditor(id);msg('已重命名为 '+renamed.name+'；权重没有变化。');error('');}catch(exc){error(exc);}}
  async function deleteModel(){const id=el('cmp-editor-source').value,row=modelById(id);if(!row||row.source!=='saved')return;if(!confirm('删除保存的评分模型“'+row.name+'”？历史对比结果仍保留。'))return;try{await api('model/delete',{id});await refreshCatalog();msg('已删除保存版本');error('');}catch(exc){error(exc);}}
  async function start(){const ids=[...selected];if(!ids.length||ids.length>48){error('请选择 1–48 份快照');return;}if(catalog.engine_consistency && catalog.engine_consistency.status!=='PASS'){error('双端引擎一致性检验未通过，暂时不能启动 A/B');return;}try{busy=true;const job=await api('start',{a_id:el('cmp-model-a').value,b_id:el('cmp-model-b').value,snapshots:ids});jobId=job.id;detailId='';await refreshCatalog();el('cmp-job-select').value=jobId;error('');}catch(exc){error(exc);}finally{busy=false;refreshJob();}}
  async function stop(){try{await api('stop',{id:jobId});text('cmp-progress','已请求停止，当前搜索结束后退出');}catch(exc){error(exc);}}
  el('cmp-editor-source').addEventListener('change',event=>loadEditor(event.target.value));el('cmp-random').addEventListener('click',randomize);el('cmp-save-model').addEventListener('click',saveModel);el('cmp-rename-model').addEventListener('click',renameModel);el('cmp-delete-model').addEventListener('click',deleteModel);el('cmp-act').addEventListener('change',renderSnapshots);el('cmp-select-all').addEventListener('click',()=>{for(const row of catalog.snapshots)if(selected.size<48&&(el('cmp-act').value==='all'||String(row.context?.act)===el('cmp-act').value))selected.add(row.id);renderSnapshots();});el('cmp-select-none').addEventListener('click',()=>{selected.clear();renderSnapshots();});el('cmp-start').addEventListener('click',start);el('cmp-stop').addEventListener('click',stop);el('cmp-job-select').addEventListener('change',event=>{jobId=event.target.value;detailId='';el('cmp-detail').textContent='选择一份结果查看动作与首次分叉。';refreshJob();});
  refreshCatalog().catch(error);setInterval(()=>{if(jobId)refreshJob();},2000);
})();
