'use strict';
const $ = id => document.getElementById(id);
const modes = {waiting_mod:'等待 Mod 更新',waiting_client:'等待客户端',idle:'就绪',preparing:'准备开局',running:'运行中',pausing:'正在暂停',paused:'已暂停',stepping:'单步执行',stopping:'正在停止',stopped:'已停止',completed:'已完成',error:'异常停止',blocked:'需要处理',recovering:'正在恢复',restarting:'重启中',manual_action_required:'等待人工操作'};
const states = {pending:'待执行',executing:'发送中',completed:'已执行',cancelled:'已撤销',outcome_unknown:'结果未知',PASS:'历史通过',COMPLETED:'已完成',DEFEAT:'战败结束',VICTORY:'胜利结束',BLOCKED:'需要处理',FAIL:'失败',WATCHDOG:'卡死中止',INTERRUPTED:'意外退出',STOPPED:'已停止',RUNNING:'运行中'};
const checks = {PASS:'覆盖字段一致',COVERED_FIELDS_MATCH:'覆盖字段一致',TERMINAL_BOUNDARY_MATCH:'战斗结束边界一致',TERMINAL_DEFEAT_MATCH:'战败结果一致',NOT_AUDITED:'未审计',FAIL:'不一致',INCOMPLETE:'信息不足',REANCHORED_PASS:'重新对齐',CLIENT_ONLY_UNVERIFIED:'客户端独立执行',UNVERIFIED:'未验证',PENDING:'待检查',NOT_EXECUTED:'未执行',ENGINE_GATE:'仅后端 · 当前局未逐步对照'};
const phases = {bootstrap:'载入影子引擎',map:'地图',before_map_choice:'地图决策',combat_decision:'计算战斗决策',before_combat_action:'动作就绪',before_reward_choice:'奖励决策',awaiting_permission:'等待执行许可',executing:'执行动作',target_reached:'目标已达到',safe_stop:'安全停止',failed:'运行失败',client_only_room:'客户端独立执行',client_only_decision:'非战斗决策'};
const policies = {bounded_combat_search:'有限深度搜索',existing_map_heuristic:'地图规则',existing_card_reward_heuristic:'启发式选牌',open_card_reward:'展开卡牌奖励'};
const interactions = {map_choice:'地图选路',combat_action:'战斗出牌',card_selection:'选择卡牌',selection_confirm:'确认选牌',reward_overview:'奖励总览',reward_card:'奖励选牌',potion_replacement:'药水替换',shop_room:'商店房间',shop_inventory:'商品面板',rest_choice:'营火选择',event_choice:'事件选择',chest_open:'开启宝箱',treasure_relic:'领取遗物',bundle_choice:'选择卡牌包',bundle_confirm:'确认卡牌包',capstone_choice:'章节选择',proceed:'继续流程',modal:'确认窗口',cards_view:'查看卡牌',main_menu:'主菜单',character_select:'角色选择',timeline:'时间线',game_over:'游戏结算',transition:'等待界面',unsupported:'未支持交互'};
function flowLabel(value){if(!value)return '尚无交互状态';const s=value.selection;return `${value.scene||'—'} → ${interactions[value.kind]||value.kind} · ${value.stage||'—'}`+(s?` · ${s.operation||'目的未知'} · 选择 ${s.minimum??'?'}–${s.maximum??'?'} 张`:'')+(value.reason?' · '+value.reason:'');}
let current = {}, report = {}, rows = [], selected = null, detailSelection = null, viewing = '', busy = false, imported = false, sessionGeneration = 0, configDirty = false, planDirty = false, loadedRevision = null, strategyModels = [];
const text = (id,value) => { $(id).textContent = value ?? '—'; };
const number = v => v === null || v === undefined ? '—' : Number(v).toFixed(1);
function element(tag, value, className) { const el=document.createElement(tag); if(value!==undefined)el.textContent=value; if(className)el.className=className; return el; }
function actionLabel(action={}) { const meta=action.metadata||{}; const name=meta.card_id||action.card_id||action.action_type||action.client_action||action.action||'—'; const params=action.client_params||action.payload||action.args||action; return name+(params.target_index!=null?' → 目标 '+params.target_index:'')+(params.card_index!=null&&!meta.card_id?' · 牌 '+params.card_index:''); }
function rowLabel(row) { const t=row.decision_telemetry||row; return t.chosen? actionLabel(t.chosen):actionLabel(row); }
function rowPosition(row){const floor=row.client_before?.run?.floor??row.client_after?.run?.floor??row.headless_before?.run?.floor??row.headless_after?.run?.floor,turn=row.client_before?.turn??row.client_after?.turn??row.headless_before?.turn,combat=row.combat_number??row.decision_telemetry?.combat_number;return '#'+(row.sequence??'—')+(floor!=null?' · '+floor+' 层':'')+(combat!=null&&turn!=null?'\n战'+combat+' 回'+turn:'');}
function verificationLabel(row={}) { const status=row.verification; if(status==='NOT_AUDITED'&&report.verification_scope==='FLOW_ONLY')return '未审计（本局未启用）'; return checks[status]||'未验证'; }
function normalize(data) {
  if(Array.isArray(data.actions))return data.actions;
  return (data.combats||[]).flatMap(c=>(c.actions||[]).map((a,i)=>({...a,sequence:'战'+c.combat_number+'-'+(a.sequence||i+1),status:'completed',decision_telemetry:a,verification:'UNVERIFIED'})));
}
function setReport(data) {
  report=data; rows=normalize(data);
  if($('follow').checked || !rows.some(r=>String(r.sequence)===String(selected))) selected=rows.at(-1)?.sequence;
  const identity=data.identity||{}, cfg=data.config||{};
  text('identity',(imported?'本地记录 · ':viewing?'历史记录 · ':'当前运行 · ')+(identity.run_id||'局编号未记录')+' · '+(identity.character||'角色未记录'));
  const strategy=strategyModels.find(item=>item.id===cfg.scoring_model_id);
  text('config',Object.keys(cfg).length?`${data.execution_mode==='headless_only'?'仅后端 · ':''}${cfg.draft_policy||'—'} · 深度 ${cfg.depth??'—'} · 软预算 ${cfg.search_budget_ms??'—'} ms · 策略 ${strategy?.name||cfg.scoring_model_id||'未记录'}`:'配置未记录');
  text('action-count',rows.length); text('combats',data.completed_combat_count??0);
  const cc=data.parity_checkpoints||[], match=cc.filter(c=>c.status==='PASS').length, bad=cc.filter(c=>['FAIL','INCOMPLETE'].includes(c.status)).length;
  text('parity-count',data.verification_scope==='FLOW_ONLY'?'流程模式':cc.length?`${match} 一致 / ${bad} 异常`:'未验证');
  renderRows(); renderDetail(); drawSearchOutcome();
}
function renderClient(c) { const run=c.run||c; text('screen',c.screen); text('position',`${run.floor??'—'} / ${c.turn??'—'}`); text('hp',`${run.current_hp??run.hp??'—'} / ${run.max_hp??'—'}`); text('gold',run.gold); }
function renderRows() {
  const body=$('timeline'); body.replaceChildren(); $('empty').hidden=rows.length>0;
  for(const row of rows){ const t=row.decision_telemetry||row, tr=element('tr'); tr.tabIndex=0; tr.classList.toggle('selected',String(row.sequence)===String(selected)); tr.setAttribute('aria-selected',String(row.sequence)===String(selected));
    for(const value of [rowPosition(row),rowLabel(row),number(t.decision_ms??t.search_ms),states[row.status]||row.status||'未知',verificationLabel(row)])tr.append(element('td',value));
    const select=()=>{selected=row.sequence;$('follow').checked=false;renderRows();renderDetail();}; tr.addEventListener('click',select);tr.addEventListener('keydown',e=>{if(e.key==='Enter')select();});body.append(tr);
  }
  if($('follow').checked)body.parentElement.parentElement.scrollTop=body.parentElement.parentElement.scrollHeight;
}
function setupCanvas(canvas){const rect=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1;canvas.width=Math.max(1,Math.round(rect.width*ratio));canvas.height=Math.max(1,Math.round(rect.height*ratio));const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);return {ctx,w:rect.width,h:rect.height};}
function searchOutcome(t={}){
  if(t.fell_back||t.decision_reason==='fallback')return 'fallback';
  if(t.decision_audit?.ran_search){
    const complete=t.decision_audit.turn_space?.bounded_tree_complete;
    return complete===true?'complete':complete===false?'incomplete':'unknown';
  }
  if(t.reused_plan||t.decision_audit?.reused_plan)return 'reused';
  if(t.decision_reason==='forced_action')return 'forced';
  return 'other';
}
const outcomeDefs=[['complete','完全搜索','#16815a'],['incomplete','不完全搜索','#2766bb'],['fallback','Fallback','#ae5b17']];
function drawSearchOutcome(){
  const counts={complete:0,incomplete:0,fallback:0,unknown:0,reused:0,forced:0};
  for(const row of rows){const kind=searchOutcome(row.decision_telemetry||row);if(Object.hasOwn(counts,kind))counts[kind]++;}
  const total=counts.complete+counts.incomplete+counts.fallback,canvas=$('search-outcome-pie'),{ctx,w,h}=setupCanvas(canvas),cx=w/2,cy=h/2,r=Math.min(w,h)*.44;
  ctx.clearRect(0,0,w,h);let angle=-Math.PI/2;
  if(!total){ctx.fillStyle='#dce2e5';ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill();}
  else for(const [key,,color] of outcomeDefs){const next=angle+Math.PI*2*counts[key]/total;if(counts[key]){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,angle,next);ctx.closePath();ctx.fill();}angle=next;}
  ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(cx,cy,r*.56,0,Math.PI*2);ctx.fill();
  ctx.fillStyle='#242b30';ctx.font='600 20px system-ui';ctx.textAlign='center';ctx.fillText(String(total),cx,cy+7);
  const legend=$('search-outcome-legend');legend.replaceChildren();
  for(const [key,label,color] of outcomeDefs){const item=element('div'),swatch=element('span',undefined,'pie-swatch');swatch.style.background=color;item.append(swatch,element('span',label+' '+counts[key]+' · '+(total?(counts[key]/total*100).toFixed(1):'0.0')+'%'));legend.append(item);}
  text('search-outcome-note','未判定 '+counts.unknown+' · 计划复用 '+counts.reused+' · 强制动作 '+counts.forced+'（均不计入比例）');
}
function budgetView(t={}){const audit=t.decision_audit||{},source=audit.turn_space?audit:(audit.origin_search||{}),limits=source.limits||{},searchMs=Number(limits.search_ms??t.search_ms)||0,budgetMs=Number(limits.time_budget_ms)||0,explicit=limits.soft_budget_overrun_ms??t.soft_budget_overrun_ms,overrun=explicit===undefined&&budgetMs>0?Math.max(0,searchMs-budgetMs):Number(explicit)||0,branchExhaustions=Number(limits.branch_budget_exhaustions??t.branch_budget_exhaustions)||0;return {limits,searchMs,budgetMs,overrun,branchExhaustions,pressure:Boolean(t.budget_pressure_detected||t.time_budget_exhausted||t.soft_budget_overrun||limits.budget_pressure_detected||limits.time_budget_exhausted||overrun>0||branchExhaustions)};}
function renderSearchQuality(t={}){
  const kind=searchOutcome(t),labels={complete:'完全搜索',incomplete:'不完全搜索',fallback:'Fallback 兜底',unknown:'完整性未判定',reused:'复用既有计划',forced:'强制动作',other:'本步没有战斗搜索'};
  text('search-status',labels[kind]);
  const turn=t.decision_audit?.turn_space||{},budget=budgetView(t),notes=[];
  if(kind==='incomplete'){
    if(Number(turn.beam_width_pruned)>0)notes.push('Beam 裁剪 '+turn.beam_width_pruned+' 条');
    if(Number(turn.depth_cutoff_leaves)>0)notes.push('深度截断 '+turn.depth_cutoff_leaves+' 处');
    if(Number(turn.unique_known_unexpanded_action_edges)>0)notes.push('已知但未展开候选 '+turn.unique_known_unexpanded_action_edges+' 条');
    if(Number(turn.failed_settlements)>0)notes.push('结算失败 '+turn.failed_settlements+' 次');
  }
  if(budget.pressure)notes.push('搜索预算受压');
  if(budget.budgetMs>0)notes.push('搜索 '+number(budget.searchMs)+' / '+number(budget.budgetMs)+' ms');
  text('search-quality',labels[kind]+(notes.length?' · '+notes.join(' · '):''));
}
function renderScoreReasons(t={}){const box=$('score-reasons'),ex=t.score_explanation||{};box.replaceChildren();if(!ex.contributions?.length){box.className='score-reasons muted';box.textContent=t.reused_plan?'复用计划未保存原始评分分项':'无评分分项';return;}box.className='score-reasons';box.append(element('div',`总分 ${number(ex.total)} · 模式 ${ex.mode||'—'}`,'score-total'));for(const item of ex.contributions){const row=element('div',undefined,'score-row');const detail=item.value===undefined?'':` (${number(item.value)} × ${number(item.weight)})`;row.append(element('span',(item.label||item.key)+detail),element('strong',(Number(item.contribution)>=0?'+':'')+number(item.contribution)));box.append(row);}}
function renderTurnSearches(){const box=$('turn-searches'),group=turnAuditRows().find(item=>item.searches.some(search=>String(search.row.sequence)===String(selected)));box.replaceChildren();if(!group){box.className='turn-searches muted';box.textContent='当前步骤不属于回合搜索';return;}box.className='turn-searches';box.append(element('strong',`战斗 ${group.combat} · 回合 ${group.turn} · 搜索 ${group.replans} 次`));const list=element('div',undefined,'turn-search-list');group.searches.forEach((search,index)=>{const button=element('button',`第 ${index+1} 次 · ${number(search.t.search_ms)} ms`);button.type='button';button.classList.toggle('selected',String(search.row.sequence)===String(selected));button.addEventListener('click',()=>{selected=search.row.sequence;$('follow').checked=false;renderRows();renderDetail();});list.append(button);});box.append(list);}
function renderDetail(){
  const row=rows.find(r=>String(r.sequence)===String(selected));
  text('detail-title',row?'步骤 '+row.sequence:'决策详情');text('chosen',row?rowLabel(row):'—');text('detail-status',row?(states[row.status]||row.status):'');
  const t=row?.decision_telemetry||row||{};
  renderTurnSearches();renderSearchQuality(t);renderScoreReasons(t);
  const selectionRule=t.decision_audit?.selection?.rule||t.decision_audit?.selection_rule||'score',selectionLabels={clean_lethal:'无代价斩杀',lower_cost_lethal:'较低代价斩杀',survival:'排除确定死亡',dominance:'严格支配',score:'评分比较'};
  const parallel=t.parallel_audit||t.decision_audit?.parallel||{},runtime=t.worker_runtime||{};
  const parallelLabel=parallel.active_workers?` · 并行 ${parallel.active_workers} worker · 根动作 ${parallel.root_jobs_completed??0}/${parallel.root_jobs_queued??0} · CPU峰值 ${number(runtime.cpu_peak_percent)}%`:'';
  text('decision-kind',row?(t.fell_back?'备用规则':t.reused_plan?'复用既有计划':t.decision_reason==='lethal_early_stop'?'斩杀使搜索提前结束':t.decision_audit?.lethal_selected?'斩杀路径为正常最高分':policies[t.policy]||t.policy||'历史记录')+(budgetView(t).pressure?' · 搜索预算受压':'')+parallelLabel:'');
  const timings=$('timings'); timings.replaceChildren();
  for(const [name,value] of [['总决策',t.decision_ms],['其中搜索',t.search_ms],['客户端执行',row?.action_wall_ms],['画面间隔',row?.visible_delay_ms],['稳定等待',row?.settle_ms],['影子引擎',row?.shadow_ms],['状态比较',row?.compare_ms]]){timings.append(element('dt',name),element('dd',number(value)+' ms'));}
  if(row&&!t.fell_back&&!t.reused_plan){const kind=$('decision-kind');kind.textContent+=` · ${selectionLabels[selectionRule]||selectionRule}`;}
  const candidates=$('candidates'); candidates.replaceChildren();
  if(!t.root_candidates?.length)candidates.append(element('p',t.reused_plan?'本步复用计划，没有重新搜索':t.fell_back?'本步采用备用规则':'没有候选记录','muted'));
  for(const c of t.root_candidates||[]){const div=element('div',undefined,'candidate'), top=element('div',undefined,'candidate-top');top.append(element('span',actionLabel(c.action)),element('strong',number(c.score)));div.append(top,element('small',(c.line||[]).map(actionLabel).join(' → ')));candidates.append(div);}
  const before=(row?.client_before||row?.headless_before)?.run,after=(row?.client_after||row?.headless_after)?.run;
  text('state-change',before&&after?`生命 ${before.current_hp} → ${after.current_hp} · 金币 ${before.gold} → ${after.gold} · 楼层 ${before.floor} → ${after.floor}`:'未记录完整的前后状态');
  const receipt=row?.reward_receipt;
  text('reward-receipt',receipt?`奖励 ${receipt.item_type||'—'} · 金币 ${receipt.gold_before??'—'} → ${receipt.gold_after??'—'} · 药水 ${(receipt.potions_before||[]).filter(p=>p.occupied).length} → ${(receipt.potions_after||[]).filter(p=>p.occupied).length}`+(receipt.skipped?.length?' · 跳过 '+receipt.skipped.map(r=>r.type+': '+r.reason).join(', '):''):'');
  text('flow-state',flowLabel(current.worker?.interaction||current.client?.interaction));
  const checkpoint=row?.checkpoint||(!row?report.latest_checkpoint:null);
  text('verification',(checks[row?.verification||checkpoint?.status]||'未验证')+' · RNG: '+(row?.rng_parity?.status||'本步未记录')+' · 完整牌堆及瞬态对象未验证');
  const diffs=$('differences');diffs.replaceChildren();
  const actionError=row?.shadow_error||row?.error;
  text('verification-brief',actionError?'动作错误':(checks[row?.verification||checkpoint?.status]||'未验证'));
  if(String(selected)!==String(detailSelection)&&row&&(actionError||['FAIL','INCOMPLETE'].includes(row.verification)))$('verification-group').open=true;
  detailSelection=selected;
  if(actionError)diffs.append(element('p',actionError));
  for(const d of checkpoint?.differences||[]){const div=element('div',undefined,'difference');div.append(element('strong',d.path),element('div','客户端: '+JSON.stringify(d.client)),element('div','影子引擎: '+JSON.stringify(d.headless)));if(d.missing)div.append(element('div','缺失: '+d.missing.join(', ')));diffs.append(div);}
  text('raw',JSON.stringify(row||report.latest_checkpoint||{},null,2));
}
function turnAuditRows(){
  const turns=new Map();
  for(const row of rows){
    const t=row.decision_telemetry||row,audit=t.decision_audit||{};
    if(!audit.ran_search)continue;
    const combat=row.combat_number??t.combat_number??'?',turn=row.client_before?.turn??audit.turn_space?.turn_number??'?',key=combat+':'+turn;
    if(!turns.has(key))turns.set(key,{combat,turn,searches:[]});
    turns.get(key).searches.push({row,t});
  }
  return [...turns.values()].map(group=>({...group,replans:group.searches.length}));
}
async function loadStrategyModels(){try{const response=await fetch('/api/comparison/models');const data=await response.json();if(!response.ok)throw Error(data.error||'无法读取策略');strategyModels=data.models||[];const select=$('scoring-model'),wanted=configDirty?select.value:(current.config?.scoring_model_id||'active');select.replaceChildren();for(const row of strategyModels)select.add(new Option(row.name,row.id));if(strategyModels.some(row=>row.id===wanted))select.value=wanted;else if(wanted)select.add(new Option('策略已删除 · '+wanted,wanted));if((report.config||{}).scoring_model_id)setReport(report);if(!$('history-details-body').hidden)renderHistory();}catch(error){text('error',String(error));$('error').hidden=false;}}
function renderStatus(data){current=data;text('connection',(data.client?.connected?'客户端已连接':'客户端未连接')+' · '+(data.runtime_version||'旧版后端'));if(data.runtime_version!=='headless-learning-20261005-1'){text('error','观察台后台进程尚未更新，请重启观察台；刷新网页不会更新后台。');$('error').hidden=false;}renderClient(data.client||{});text('mode',modes[data.mode]||data.mode);$('mode').className='badge '+data.mode;text('phase',phases[data.worker?.phase]||data.worker?.phase||'');text('message',data.worker?.error||data.message||'');text('live-run-id',data.client?.run_id?`本局 ${data.client.run_id} · 第 ${data.client.floor??'—'} 层`:'尚无当前局');text('active-strategy',data.active_scoring_model_id?'本局策略：'+(strategyModels.find(row=>row.id===data.active_scoring_model_id)?.name||data.active_scoring_model_id):'');text('view-context',imported?'正在查看本地导入记录':viewing?'正在查看历史记录 · 上方按钮仅控制当前局':'当前记录');
  renderHeadlessBatch(data);
  if(data.history_only){text('mode','历史维护');text('message','此窗口不控制运行中的对局');}
  text('flow-state',flowLabel(data.worker?.interaction||data.client?.interaction));
  const active=!!data.worker_running, preparing=!!data.preparing||!!data.recovering;
  for(const id of ['pause','resume','step','stop','start','restart','menu'])$(id).disabled=busy||data.history_only;
  $('start').disabled ||= active||preparing||['running','stopping'].includes(data.headless_batch?.status);$('pause').disabled ||= (!active&&!data.auto_start&&!preparing)||data.auto_paused||data.mode==='paused';$('resume').disabled ||= !data.auto_paused&&(!active||data.mode!=='paused');$('step').disabled ||= !active||data.mode!=='paused';$('stop').disabled ||= !active&&!preparing&&!data.auto_start;$('restart').disabled ||= preparing||data.mode==='restarting';$('menu').disabled ||= active||preparing;
  $('continue').disabled=busy||data.history_only||active||preparing||!data.session_id||['GAME_OVER','MAIN_MENU'].includes(data.client?.screen);
  for(const id of ['depth','search','worker-mode','workers','delay','stall','scoring-model'])$(id).disabled=data.history_only||active||preparing;
  const cfg=data.config||{};
  for(const [id,key] of [['stall','stall_seconds'],['depth','depth'],['search','search_ms'],['workers','max_workers'],['delay','delay_ms']]){
    if(!configDirty&&cfg[key]!=null&&document.activeElement!==$(id))$(id).value=cfg[key];
  }
  if(!configDirty&&cfg.worker_mode&&document.activeElement!==$('worker-mode'))$('worker-mode').value=cfg.worker_mode;if(!configDirty&&cfg.scoring_model_id&&[...$('scoring-model').options].some(row=>row.value===cfg.scoring_model_id))$('scoring-model').value=cfg.scoring_model_id;
  const plan=data.run_plan||{};if(!planDirty&&!busy){$('run-mode').value=plan.mode||'single';if(plan.target>0)$('batch-target').value=plan.target;}$('batch-target-label').hidden=$('run-mode').value!=='batch';$('apply-plan').disabled=busy||data.history_only||!active||preparing||!!data.snapshot_busy;$('run-mode').disabled=busy||data.history_only;$('batch-target').disabled=busy||data.history_only||$('run-mode').value!=='batch';const batchState=({running:'进行中',paused:'已暂停',completed:'已完成',cancelled:'已取消',interrupted:'观察台重启后中断'})[plan.state]||'未开始';const currentNumber=plan.mode==='batch'&&['running','paused'].includes(plan.state)&&plan.completed<plan.target?` · 第 ${Number(plan.completed)+1} 局${active?'正在运行':'待开始'}`:'';const progress=plan.mode==='batch'?`已结束 ${plan.completed??0} / ${plan.target??0} 局${currentNumber} · ${batchState}`:plan.mode==='unlimited'?'无限连续运行':'单局运行';text('batch-progress',progress+(planDirty?' · 选择尚未应用':''));$('save-config').disabled=busy||data.history_only||active||preparing;$('shutdown').disabled=data.history_only;
  if(data.snapshot_busy)for(const id of ['pause','resume','step','stop','start','restart','menu','continue','apply-plan','shutdown'])$(id).disabled=true;
  const capture=$('snapshot-capture');if(capture){capture.hidden=!!data.history_only;capture.disabled=busy||capture.dataset.busy==='true'||!!data.snapshot_busy||preparing||data.client?.interaction?.kind!=='combat_action'||(active&&data.mode!=='paused')||(data.auto_start&&!data.auto_paused);}
  text('limitation',data.client?.screen&&!['MAIN_MENU','GAME_OVER'].includes(data.client.screen)?'局内恢复需要新版恢复桥接':'');
  const id=viewing||data.session_id;for(const [button,file] of [['download','run_report.json'],['download-log','session.jsonl']]){const a=$(button);a.setAttribute('aria-disabled',!id||imported?'true':'false');if(id&&!imported){a.href='/api/download?id='+encodeURIComponent(id)+'&file='+file;a.download=file;}else a.removeAttribute('href');}
}
async function request(command){if(busy)return;const mode=$('run-mode').value,target=Number($('batch-target').value);if(['start','set_run_plan'].includes(command)&&mode==='batch'&&(!Number.isSafeInteger(target)||target<1)){text('error','局数 N 必须是正整数');$('error').hidden=false;return;}const options={stall_seconds:+$('stall').value,depth:+$('depth').value,search_ms:+$('search').value,worker_mode:$('worker-mode').value,scoring_model_id:$('scoring-model').value,max_workers:+$('workers').value,delay_ms:+$('delay').value,expected_session_id:current.session_id??null};if(['start','set_run_plan'].includes(command)){options.run_mode=mode;options.batch_target=target;}busy=true;$('error').hidden=true;renderStatus(current);try{const response=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command,options})});const data=await response.json();if(!response.ok)throw Error(data.error);if(command==='shutdown'){text('message','观察台正在关闭');return;}if(command==='save_config'){configDirty=false;text('config-saved','已保存');}if(['start','set_run_plan'].includes(command))planDirty=false;renderStatus(data);}catch(e){text('error',String(e));$('error').hidden=false;}finally{busy=false;renderStatus(current);}}
async function loadSession(id){const generation=++sessionGeneration;viewing=id;imported=false;selected=null;if(!id){loadedRevision=null;setReport({});renderStatus(current);return;}try{const r=await fetch('/api/session?id='+encodeURIComponent(id));if(!r.ok)throw Error('无法读取运行记录');const data=await r.json();if(generation!==sessionGeneration)return;setReport(data);renderStatus(current);}catch(e){text('error',String(e));$('error').hidden=false;}}
async function refresh(){try{const previousSession=current.session_id,previousRunning=current.worker_running,previousHeadless=current.headless_batch?.completed;const r=await fetch('/api/status');renderStatus(await r.json());if($('history-body').hidden===false&&(previousSession!==current.session_id||(previousRunning&&!current.worker_running)||previousHeadless!==current.headless_batch?.completed)){loadHistorySummary();if($('history-details-body').hidden===false)loadHistory(true);}const generation=sessionGeneration;if(!viewing&&!imported&&current.session_id&&(!current.report_revision||loadedRevision!==current.report_revision)){const revision=current.report_revision;const response=await fetch('/api/session?id='+encodeURIComponent(current.session_id));const data=await response.json();if(response.ok&&generation===sessionGeneration&&!viewing&&!imported){setReport(data);loadedRevision=revision;}}
}catch(e){text('connection','观察台连接断开');}finally{setTimeout(refresh,1000);}}
for(const id of ['start','pause','resume','step','stop','restart','menu','shutdown'])$(id).addEventListener('click',()=>request(id==='menu'?'return_to_menu':id));
$('continue').addEventListener('click',()=>request('continue_session'));
$('apply-plan').addEventListener('click',()=>request('set_run_plan'));$('run-mode').addEventListener('change',()=>{planDirty=true;$('batch-target-label').hidden=$('run-mode').value!=='batch';$('batch-target').disabled=$('run-mode').value!=='batch';});$('batch-target').addEventListener('input',()=>{planDirty=true;});$('sessions').addEventListener('change',e=>{if(e.target.value!=='__imported__')loadSession(e.target.value);});$('live').addEventListener('click',()=>{$('sessions').value='';loadSession('');});$('follow').addEventListener('change',()=>setReport(report));$('import').addEventListener('click',()=>$('file').click());
function reportFromEvents(events){const actions=new Map();for(const event of events){if(event.sequence==null)continue;const previous=actions.get(event.sequence)||{};
  if(['action_pending','action_started','live_action','client_only_action','action_failed'].includes(event.event))actions.set(event.sequence,{...previous,...event});
  else if(event.event==='shadow_advance'&&actions.has(event.sequence))previous.shadow_ms=event.shadow_ms;
  else if(event.event==='parity_checkpoint'&&actions.has(event.sequence)){const action=actions.get(event.sequence);action.checkpoint=event;action.compare_ms=event.compare_ms;action.verification=event.status==='PASS'?'COVERED_FIELDS_MATCH':event.status;}else if(event.event==='terminal_outcome'&&actions.has(event.sequence)){actions.get(event.sequence).verification=event.verification||'TERMINAL_BOUNDARY_MATCH';}}
  return {status:'IMPORTED',actions:[...actions.values()],parity_checkpoints:events.filter(e=>e.event==='parity_checkpoint')};}
$('file').addEventListener('change',async e=>{try{const content=await e.target.files[0].text();let data;try{data=JSON.parse(content);}catch{data=reportFromEvents(content.trim().split(/\r?\n/).map(line=>JSON.parse(line)));}if(!data||typeof data!=='object'||Array.isArray(data))throw Error('无效运行记录');sessionGeneration++;viewing='';imported=true;selected=null;$('sessions').add(new Option('本地导入记录','__imported__'));$('sessions').value='__imported__';setReport(data);renderStatus(current);}catch(error){text('error',String(error));$('error').hidden=false;}finally{e.target.value='';}});
window.addEventListener('resize',drawSearchOutcome);lucide.createIcons();loadStrategyModels();refresh();
const historyRows=[];let historyOffset=0,historyHasMore=true,historyLoading=false,historyGeneration=0,summaryGeneration=0,historySummary=null,historyCategory='defeat',historyReloadPending=false;
const historyDefs=[['victory','胜利','#16815a'],['defeat','战败','#d58427'],['stopped','停止','#75828a'],['error','错误','#bb3737']];
function openHistoryRecord(row){const select=$('sessions');if(![...select.options].some(option=>option.value===row.id))select.add(new Option(row.id+' · '+(states[row.status]||row.status),row.id));select.value=row.id;loadSession(row.id);document.querySelector('.metrics').scrollIntoView({behavior:'smooth',block:'start'});}
function renderHistory(){const body=$('run-history');body.replaceChildren();for(const row of historyRows){const tr=element('tr');tr.tabIndex=0;tr.classList.toggle('run-error',!!row.error&&row.status!=='STOPPED');const model=strategyModels.find(item=>item.id===row.scoring_model_id),result=row.status==='STOPPED'?'已停止':row.error?'错误':states[row.status]||row.status;for(const value of [new Date((row.finished_at||row.created_at)*1000).toLocaleString(),result+(row.execution_mode==='headless_only'?' · 仅后端':''),model?.name||row.scoring_model_id||'未记录',row.floor??'—',row.deck_size??'—'])tr.append(element('td',value));const cell=element('td'),remove=element('button');remove.type='button';remove.className='history-delete';remove.title='永久删除此局及全部日志';remove.setAttribute('aria-label','删除 '+new Date(row.created_at*1000).toLocaleString()+' 的对局记录');remove.innerHTML='<i data-lucide="trash-2"></i>';remove.disabled=busy||row.id===current.session_id;remove.addEventListener('click',event=>{event.stopPropagation();deleteHistory(row);});cell.append(remove);tr.append(cell);tr.onclick=()=>openHistoryRecord(row);tr.onkeydown=e=>{if(e.key==='Enter'&&e.target===tr)openHistoryRecord(row);};body.append(tr);}if(!historyRows.length&&!historyLoading){const tr=element('tr'),td=element('td','暂无已结束对局','history-empty');td.colSpan=6;tr.append(td);body.append(tr);}lucide.createIcons();}
function drawHistorySummary(){const summary=historySummary;if(!summary)return;const counts=summary.counts||{},actual=summary.actual||0;text('history-summary-status',`最近 ${summary.requested} 局，实际纳入 ${actual} 局`);const canvas=$('history-pie'),ctx=canvas.getContext('2d'),cx=120,cy=120,r=105;ctx.clearRect(0,0,240,240);let angle=-Math.PI/2;for(const [key,,color] of historyDefs){const count=counts[key]||0;if(!count||!actual)continue;const next=angle+count/actual*Math.PI*2;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,angle,next);ctx.closePath();ctx.fillStyle=color;ctx.fill();angle=next;}if(!actual){ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fillStyle='#e8edef';ctx.fill();}ctx.beginPath();ctx.arc(cx,cy,55,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.fillStyle='#242b30';ctx.textAlign='center';ctx.font='bold 22px system-ui';ctx.fillText(String(actual),cx,cy+7);const legend=$('history-legend');legend.replaceChildren();for(const [key,label,color] of historyDefs){const count=counts[key]||0,button=element('button',`${label} ${count} · ${actual?(count/actual*100).toFixed(1):'0.0'}%`);button.type='button';button.className='history-legend-button';button.setAttribute('aria-pressed',String(historyCategory===key));const dot=element('span',undefined,'pie-swatch');dot.style.background=color;button.prepend(dot);button.onclick=()=>{historyCategory=key;drawHistorySummary();};legend.append(button);}renderHistoryBreakdown();}
function renderHistoryBreakdown(){const box=$('history-breakdown'),summary=historySummary;box.replaceChildren();if(!summary)return;const label=historyDefs.find(item=>item[0]===historyCategory)?.[1];box.append(element('h4',label+'详情'));if(historyCategory==='error'){const errors=summary.errors||[];if(!errors.length){box.append(element('p','没有错误记录','muted'));return;}errors.forEach((group,i)=>{const item=element('div',undefined,'history-error-group');item.append(element('strong',`${i+1}. ${group.reason} · ${group.count} 次`));if(group.example)item.append(element('p','示例：'+group.example,'muted'));for(const row of group.records||[]){const button=element('button',`${new Date(row.created_at*1000).toLocaleString()} · 第 ${row.floor??'—'} 层`);button.onclick=()=>openHistoryRecord(row);item.append(button);}box.append(item);});return;}if(historyCategory==='defeat'){const d=summary.defeat||{},n=d.count||0;box.append(element('p',`平均达到 ${d.average_floor==null?'—':d.average_floor.toFixed(1)} 层 · 第一幕通过 ${n?(d.act1_passed/n*100).toFixed(1):'0.0'}% · 第二幕通过 ${n?(d.act2_passed/n*100).toFixed(1):'0.0'}%`));box.append(element('h5','最高楼层 Top 3'));for(const row of d.top||[]){const button=element('button',`第 ${row.floor??'—'} 层 · 种子 ${row.seed||'未记录'} · ${row.deck_size??'—'} 张牌`);button.onclick=()=>openHistoryRecord(row);box.append(button);}return;}box.append(element('p',`共 ${summary.counts?.[historyCategory]||0} 局`));}
async function loadHistorySummary(){if($('history-body').hidden)return;const generation=++summaryGeneration;text('history-summary-status','正在统计最近对局…');try{const result=await fetch(`/api/sessions?offset=0&limit=0&summary_n=${$('history-count').value}`),data=await result.json();if(!result.ok)throw Error(data.error||'无法读取历史概览');if(generation!==summaryGeneration)return;historySummary=data.summary;drawHistorySummary();}catch(error){if(generation===summaryGeneration)text('history-summary-status',String(error));}}
async function loadHistory(reset=false){if($('history-details-body').hidden)return;if(historyLoading){if(reset)historyReloadPending=true;return;}if(reset){historyGeneration++;historyRows.length=0;historyOffset=0;historyHasMore=true;renderHistory();}if(!historyHasMore)return;const generation=historyGeneration;historyLoading=true;text('history-load-status','正在读取历史记录…');try{const result=await fetch(`/api/sessions?offset=${historyOffset}&limit=20&summary_n=${$('history-count').value}`),data=await result.json();if(!result.ok)throw Error(data.error||'无法读取历史记录');if(generation!==historyGeneration)return;historyOffset=data.next_offset;historyHasMore=!!data.has_more;for(const row of data.sessions||[])if(!historyRows.some(item=>item.id===row.id))historyRows.push(row);renderHistory();text('history-load-status',historyHasMore?'向下滚动加载更早记录':`已显示 ${historyRows.length} 条记录`);}catch(error){text('history-load-status',String(error));}finally{historyLoading=false;if(historyReloadPending){historyReloadPending=false;loadHistory(true);}}}
async function deleteHistory(row){if(busy||row.id===current.session_id)return;const when=new Date(row.created_at*1000).toLocaleString();if(!confirm(`永久删除 ${when} 的对局记录？\n该局的完整报告、原始日志与快照都会删除，无法恢复。`))return;busy=true;try{const response=await fetch('/api/sessions/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id})});const result=await response.json();if(!response.ok)throw Error(result.error||'删除失败');if(viewing===row.id){$('sessions').value='';await loadSession('');}const option=[...$('sessions').options].find(item=>item.value===row.id);option?.remove();busy=false;await Promise.all([loadHistory(true),loadHistorySummary()]);}catch(error){text('error',String(error));$('error').hidden=false;}finally{busy=false;renderStatus(current);}}
const historyToggle=$('history-toggle'),historyBody=$('history-body'),detailsToggle=$('history-details-toggle'),detailsBody=$('history-details-body');
historyToggle.addEventListener('click',()=>{const expanded=historyToggle.getAttribute('aria-expanded')!=='true';historyToggle.setAttribute('aria-expanded',String(expanded));historyBody.hidden=!expanded;if(expanded){loadHistorySummary();if(!detailsBody.hidden)loadHistory(true);}});
detailsToggle.addEventListener('click',()=>{const expanded=detailsToggle.getAttribute('aria-expanded')!=='true';detailsToggle.setAttribute('aria-expanded',String(expanded));detailsBody.hidden=!expanded;if(expanded)loadHistory(true);});
$('history-count').addEventListener('change',loadHistorySummary);
$('history-scroll').addEventListener('scroll',()=>{const el=$('history-scroll');if(!historyLoading&&historyHasMore&&el.scrollTop+el.clientHeight>=el.scrollHeight-180)loadHistory();});
$('history-pie').addEventListener('click',event=>{if(!historySummary?.actual)return;const rect=event.currentTarget.getBoundingClientRect(),x=(event.clientX-rect.left)*240/rect.width-120,y=(event.clientY-rect.top)*240/rect.height-120;if(x*x+y*y>105*105||x*x+y*y<55*55)return;let angle=Math.atan2(y,x)+Math.PI/2;if(angle<0)angle+=Math.PI*2;let end=0;for(const [key] of historyDefs){end+=(historySummary.counts[key]||0)/historySummary.actual*Math.PI*2;if(angle<=end){historyCategory=key;drawHistorySummary();break;}}});
$('history-pie').addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();const index=historyDefs.findIndex(item=>item[0]===historyCategory);historyCategory=historyDefs[(index+1)%historyDefs.length][0];drawHistorySummary();}});
function renderHeadlessBatch(data){const batch=data.headless_batch||{},active=['running','stopping'].includes(batch.status),done=Number(batch.completed||0),target=Number(batch.target||0);$('headless-start').disabled=busy||data.history_only||!data.headless_only_allowed||active||data.worker_running||data.preparing;$('headless-stop').disabled=busy||data.history_only||!active||batch.status==='stopping';$('headless-count').disabled=active;$('headless-parallel').disabled=active;$('headless-progress-bar').value=target?Math.round(done/target*100):0;text('headless-progress',target?`已结束 ${done} / ${target} 局 · 正在运行 ${batch.running||0} 局 · ${batch.message||batch.status}`:'尚未启动');}
async function headlessCommand(kind){if(busy)return;const count=Number($('headless-count').value),parallel=Number($('headless-parallel').value);if(kind==='start'&&(!Number.isSafeInteger(count)||count<1||count>1000||!Number.isSafeInteger(parallel)||parallel<1||parallel>4)){text('headless-message','总局数需为 1–1000，并行局数需为 1–4');return;}busy=true;text('headless-message','');renderHeadlessBatch(current);try{const response=await fetch('/api/headless-runs/'+kind,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({count,parallel,scoring_model_id:$('scoring-model').value})});const result=await response.json();if(!response.ok)throw Error(result.error||'操作失败');text('headless-message',result.message||'已提交');const status=await fetch('/api/status');if(status.ok)renderStatus(await status.json());}catch(error){text('headless-message',String(error));}finally{busy=false;renderHeadlessBatch(current);}}
$('headless-start').addEventListener('click',()=>headlessCommand('start'));
$('headless-stop').addEventListener('click',()=>headlessCommand('stop'));
$('save-config').addEventListener('click',()=>request('save_config'));
for(const id of ['depth','search','worker-mode','workers','delay','stall','scoring-model'])$(id).addEventListener('input',()=>{configDirty=true;text('config-saved','有未保存参数');});
