'use strict';
const $=id=>document.getElementById(id);
const modeLabels={idle:'Ready',collecting:'Collecting',working:'Working',stopping:'Stopping',completed:'Completed',error:'Failed'};
let current={},sessions=[],selected='',busy=false,poll=0;
const setText=(id,value)=>{$(id).textContent=value??'-';};
const fmtTime=value=>value?new Date(value).toLocaleString():'-';
function renderEndpoint(prefix,value){const connected=!!value?.connected;setText(prefix+'-status',connected?'Connected':'Disconnected');$(prefix+'-status').className=connected?'ok':'bad';const data=value?.data||{};setText(prefix+'-detail',connected?(data.protocol_version||'ready')+(data.patch_count!=null?' / '+data.patch_count+' patches':''):(value?.error||'Waiting for game'));}
function renderPipelineProgress(data){const job=data.job,active=job==='generate_current'||job==='train_current',box=$('pipeline-progress-box');box.hidden=!active;if(!active)return;const learning=data.current_learning||{},report=job==='generate_current'?learning.generation_report||{}:learning.training_progress||{};const total=job==='generate_current'?Number(report.turns||0):Number(report.total||0),done=job==='generate_current'?Number(report.completed_turns||0)+Number(report.failed_turns||0):Number(report.completed||0),percent=total?Math.min(100,Math.round(done/total*100)):0;$('pipeline-progress').value=percent;setText('pipeline-progress-label',job==='generate_current'?'生成回合叶节点':report.phase||'训练评分参数');setText('pipeline-progress-count',`${done} / ${total||'?'} · ${percent}%${data.running?'':data.mode==='error'?' · 任务失败':' · 已结束'}`);}
function renderStatus(data){current=data;const running=!!data.running,collecting=data.job==='collect'&&running;setText('top-status',running?(data.job||'task')+' running':'Controller connected');setText('mode',modeLabels[data.mode]||data.mode);$('mode').className='badge '+data.mode;setText('message',data.message);setText('job-name',data.job||'No active task');setText('log',(data.recent_log||[]).join('\n')||'Waiting');setText('result',JSON.stringify(data.last_result||{},null,2));
  const install=data.installation||{},installed=install.installed,matches=install.matches_build;setText('install-status',matches?'Current build installed':installed?'Installed build differs':'Not installed');$('install-status').className=matches?'ok':installed?'warn':'bad';setText('install-detail',matches?(install.installed_sha256||'').slice(0,16):install.installed_path||'');$('install-action').hidden=matches;setText('install-command',install.install_command||'');
  renderEndpoint('observer',data.observer);renderEndpoint('capture',data.capture);setText('active-session',data.latest_session_id?'Latest '+data.latest_session_id:'');renderPipelineProgress(data);
  const learning=data.current_learning||{},report=learning.join_report||{};const ready=!!data.observer?.connected&&!!data.capture?.connected;$('start').disabled=busy||running||!ready;$('stop').disabled=busy||!collecting;$('max-actions').disabled=running;$('audit').disabled=busy||running||!selected;$('delete-session').disabled=busy||running||!selected;$('delete-incompatible').disabled=busy||running||!sessions.some(x=>x.historical);$('generate-current').disabled=busy||running||!sessions.some(x=>!x.historical&&x.status!=='failed');$('join-current').disabled=busy||running||!learning.leaf_exists;$('train-current').disabled=busy||running||!report.matches_path||!(report.fit_ready_rows>0);$('strict').disabled=running;const progress=learning.generation_report||{};setText('dataset-summary','Turns '+(progress.completed_turns||0)+' / '+(progress.turns||0)+'; exhaustive '+(progress.exhaustive_turns||0)+'; leaves '+(progress.leaves||0)+'; fit-ready '+(report.fit_ready_rows||0));
}
function renderSessions(){const box=$('session-list');box.replaceChildren();$('session-empty').hidden=!!sessions.length;for(const item of sessions){const button=document.createElement('button');button.className='session-item'+(item.id===selected?' selected':'');button.type='button';const left=document.createElement('span'),name=document.createElement('strong'),meta=document.createElement('small'),size=document.createElement('span');name.textContent=item.id;meta.textContent=(item.historical?'Incompatible snapshot schema / ':'')+(item.status||'unknown')+' / '+fmtTime(item.closed_at_utc||item.started_at_utc);size.textContent=Math.max(1,Math.round((item.bytes||0)/1024))+' KB';left.append(name,meta);button.append(left,size);button.addEventListener('click',()=>selectSession(item.id));box.append(button);}}
function clearSessionDetail(){setText('audit-state','Not selected');$('audit-state').className='badge';['records','decisions','settled','patches'].forEach(id=>setText(id,'-'));$('actions').textContent='-';$('actions').className='counts muted';$('sources').textContent='-';$('sources').className='counts muted';setText('integrity','Select a session');$('integrity').className='integrity muted';}
function renderCounts(id,value){const box=$(id);box.replaceChildren();const entries=Object.entries(value||{});box.className='counts'+(entries.length?'':' muted');if(!entries.length){box.textContent='-';return;}for(const [name,count] of entries){const item=document.createElement('span');item.textContent=name+' '+count;box.append(item);}}
async function selectSession(id){selected=id;renderSessions();try{const response=await fetch('/api/human-capture/session?id='+encodeURIComponent(id));const data=await response.json();if(!response.ok)throw Error(data.error||'Cannot read session');const audit=data.audit||{};setText('audit-state',audit.ok?'Integrity passed':'Needs review');$('audit-state').className='badge '+(audit.ok?'completed':'error');setText('records',audit.records);setText('decisions',audit.decisions);setText('settled',audit.settlements?.settled||0);setText('patches',audit.patch_count);renderCounts('actions',audit.actions);renderCounts('sources',audit.sources);const problems=[...(audit.integrity_errors||[]),...(audit.missing_required_cases||[]).map(value=>'Missing '+value)];setText('integrity',problems.length?problems.join('\n'):'Protocol, continuity and snapshots passed');$('integrity').className='integrity '+(problems.length?'bad':'ok');}catch(error){showError(error);}}
function showError(error){setText('error',String(error));$('error').hidden=false;}
async function command(name,options={}){if(busy)return;busy=true;$('error').hidden=true;try{const response=await fetch('/api/human-capture/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command:name,options})});const data=await response.json();if(!response.ok)throw Error(data.error||'Command failed');renderStatus(data);if(name==='delete_session'||name==='delete_incompatible'){selected='';clearSessionDetail();await loadSessions();}else if(name==='stop'||name==='audit'||name==='generate_current'||name==='join_current'||name==='train_current')setTimeout(loadSessions,500);}catch(error){showError(error);}finally{busy=false;renderStatus(current);}}
async function loadSessions(){try{const response=await fetch('/api/human-capture/sessions');const data=await response.json();if(!response.ok)throw Error(data.error||'Cannot read sessions');sessions=data.sessions||[];if(selected&&!sessions.some(item=>item.id===selected))selected='';renderSessions();}catch(error){showError(error);}}
async function refresh(){try{const response=await fetch('/api/human-capture/status');const data=await response.json();if(!response.ok)throw Error(data.error||'Status failed');renderStatus(data);if(poll++%4===0)await loadSessions();if(selected&&poll%8===0)await selectSession(selected);}catch(error){setText('top-status','Dashboard disconnected');}finally{setTimeout(refresh,1000);}}
$('start').addEventListener('click',()=>command('start',{max_actions:$('max-actions').value||null}));$('stop').addEventListener('click',()=>command('stop'));$('audit').addEventListener('click',()=>command('audit',{session_id:selected,strict:$('strict').checked}));$('generate-current').addEventListener('click',()=>command('generate_current'));$('join-current').addEventListener('click',()=>command('join_current'));$('train-current').addEventListener('click',()=>command('train_current'));$('delete-incompatible').addEventListener('click',()=>{if(window.confirm('Delete all incompatible snapshot sessions? This cannot be undone.'))command('delete_incompatible',{confirm:true});});$('delete-session').addEventListener('click',()=>{if(!selected)return;if(window.confirm('Delete session '+selected+'?'))command('delete_session',{session_id:selected,confirm:true});});$('refresh-sessions').addEventListener('click',loadSessions);lucide.createIcons();refresh();
